In [1]:
import numpy as np
import pandas as pd

In [6]:
data = pd.read_csv('/content/PlayTennis.csv')
data

     outlook  temp humidity  windy play
0      sunny   hot     high  False   no
1      sunny   hot     high   True   no
2   overcast   hot     high  False  yes
3      rainy  mild     high  False  yes
4      rainy  cool   normal  False  yes
5      rainy  cool   normal   True   no
6   overcast  cool   normal   True  yes
7      sunny  mild     high  False   no
8      sunny  cool   normal  False  yes
9      rainy  mild   normal  False  yes
10     sunny  mild   normal   True  yes
11  overcast  mild     high   True  yes
12  overcast   hot   normal  False  yes
13     rainy  mild     high   True   no

In [7]:
 # Problem 1
 # Outlook=sunny,temp=hot,humidity=high,wind=weak
 # play or No play?

In [8]:
# Solution
# P(yes|sunny,hot,high,weak) = P(sunny|yes) * P(hot|yes) * P(high|yes) * P(weak|yes) * P(yes)
# P(No|sunny,hot,high,weak) = P(sunny|No) * P(hot|No) * P(high|No) * P(weak|No) * P(yes)
# Campare and decide using the maximum a posterior rule

In [9]:
# Problem 2
# Outlook=overscat,temp=cold,humidity=low,wind=weak
 # play or No play?

In [10]:
# Solution
# P(yes|Overcast,cold,low,weak) = P(overcast|yes) * P(cold|yes) * P(low|yes) * P(weak|yes) * P(yes)
# P(No|sunny,hot,high,weak) = P(overcast|No) * P(hot|No) * P(cold|No) * P(low|No) * P(yes)
# Campare and decide using the maximum a posterior rule

In [11]:
# Traing:Lookup Table(Dictionary)
# Testing

In [12]:
# P(Yes)
# P(No)

In [13]:
data['play'].value_counts()

play
yes    9
no     5
Name: count, dtype: int64

In [14]:
py = 9 /14 # P(Yes)
pn =  5 / 14 # P(No)

In [15]:
py

0.6428571428571429

In [16]:
pn

0.35714285714285715

In [17]:
# Outlook
pd.crosstab(data['outlook'],data['play'])

play      no  yes
outlook
overcast   0    4
rainy      2    3
sunny      3    2

In [19]:
Pon = 0
Prn = 2/5
Psn = 3/5
Poy = 4/9
Pry = 3/9
Psy = 2/9

In [20]:
# Outlook
pd.crosstab(data['temp'],data['play'])

play  no  yes
temp
cool   1    3
hot    2    2
mild   2    4

In [21]:
PcoolNo = 1 /5
PhotNo = 2/5
PmildNo=2/5
PcoolYes= 2/9
PhotYes = 2/9
PmildYes = 4/9

In [22]:
# Outlook
pd.crosstab(data['humidity'],data['play'])

play      no  yes
humidity
high       4    3
normal     1    6

In [23]:
PNoramlNo = 1/5
PhighNo = 4/5
PhighYes = 3/9
PhighYes = 6/9

In [25]:
# Outlook
pd.crosstab(data['windy'],data['play'])

play   no  yes
windy
False   2    6
True    3    3

In [26]:
PStrongNo = 3/5
PWeakNo = 2/5
PWeakYes = 6/9
PStrongYes = 3/9

In [36]:
# Outlook=sunny,temp=hot,humidity=high,wind=weak
 # play or No play?
Pyes = py*Psy*PhotYes*PhighYes*PWeakYes

In [33]:
Pyes

0.014109347442680775

In [34]:
Pno = pn * PhotNo * Psn * PhighNo * PWeakNo

In [35]:
Pno

0.027428571428571438

In [37]:
# No Play